{% set version = "0.34.0" %}

package:
  name: pixman
  version: {{ version }}

source:
  fn: pixman-{{ version }}.tar.gz
  url: http://cairographics.org/releases/pixman-{{ version }}.tar.gz
  sha256: 21b6b249b51c6800dc9553b65106e1e37d0e25df942c90531d4c3997aa20a88e
  patches:
    - no_test.patch  # [win]

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - python  # [win]
    - posix  # [win]
    - pkg-config  # [not win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]

test:
  commands:
    - test -f ${PREFIX}/lib/libpixman-1.a  # [not win]
    #- conda inspect linkages -p $PREFIX pixman  # [not win]
    #- conda inspect objects -p $PREFIX pixman  # [osx]

about:
  home: http://www.pixman.org/
  license: MIT
  license_file: COPYING
  summary: 'A low-level software library for pixel manipulation.'
  description: |
    Pixman is a low-level software library for pixel manipulation, providing
    features such as image compositing and trapezoid rasterization.
  dev_url: https://cgit.freedesktop.org/pixman/

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
